### ISSUE TITLE
Blank admin tool

### ISSUE THREAD

**Issue by emmalivingstone** [nstudio/xplat-issues#1]
I followed the instructions on the xplat blog post to setup a new workspace - I added a web app and a NativeScript app but when I open the admin tool it just shows:

![image](https://user-images.githubusercontent.com/29950128/38777602-c19689ba-40a2-11e8-9d70-6cee0c42b5f7.png)

Also if I try to run `ng g mode fullstack` I get the error: 

IDE Settings could not be updated at this time: { Error: EISDIR:
illegal operation on a directory, read
    at Object.fs.readSync (fs.js:675:18)
    at tryReadSync (fs.js:540:20)
    at Object.fs.readFileSync (fs.js:583:19)
    at Object.updateIDESettings

**Comment by NathanWalker** [comment]
Thank you for tracking. I can see you’re on Windows, what version? From looks of error message it may be having trouble finding the IDE settings.

**Comment by emmalivingstone** [comment]
I'm on Windows 10 using VS Code.

**Comment by iztokb** [comment]
Yep I have exactly the same problem on Windows 10 Enterprise. 

If I do console.log(process.env.APPDATA), I get  C:\Users\user.MYDOMAIN\AppData\Roaming

If I change userSettingsPath  in utils.js file to:

```js
const userSettingsPath =
      process.env.APPDATA + process.platform == 'win32'
        ? '\\code'
        : '' ||
          (process.platform == 'darwin'
            ? process.env.HOME +
              `/Library/Application Support/Code/User/settings.json`
            : '/var/local/Cole/User/settings.json');
```
it doesn't throw error. I just get update tsconfig.json 

However, admin tool is still blank.

**Comment by NathanWalker** [comment]
Thanks @iztokb - I have this fixed locally but looking at an issue on Window's related to mode switching. Once that's clear I'll get the fix published.

**Comment by NathanWalker** [comment]
`0.1.8` is published now which should solve this. @emmalivingstone lemme know if you find other issues. I'm working on improving the admin start/stop controls on apps. Right now on windows looks like we get no console output even if a web app does in fact spin up just fine.
