### ISSUE TITLE
Support for  6 (Angular and Nx) 

### ISSUE THREAD

**Issue by netwobble** [nstudio/xplat-issues#11]
Hey folks,
Just a question on support for v6 angular and Nx?  Nx has done a lot of work to align the v6 support (currently in rc3). Will these changes affect the xPlat schematic’s?  Will you be releasing updates?

Cheers,
AJ

**Comment by SociallyAdequateGeek** [comment]
With the next release of nx coming very soon; @NathanWalker or @jeffwhelpley, do you have a pre-release version of xplat targeting the nx rc3 version in flight?

**Comment by NathanWalker** [comment]
@nstudio/schematics 6.0.0-rc.1 works with it 👍

It will be version aligned with major version releases of Angular like Nx (minor version may differ however will still work)
