### ISSUE TITLE
How to get 'ng test' to run spec files from the xplat/libs directory?

### ISSUE THREAD

**Issue by emmalivingstone** [nstudio/xplat-issues#12]
So I have a `.spec.ts` file in the xplat/features directory but it's not being included when I run `ng test` on the workspace directory, is there some configuration you need to include it?

**Comment by NathanWalker** [comment]
@emmalivingstone thank you - with the recent Nx v6 changes each lib module (and xplat setup) appears to generate it's own and I may need to include the setup when the structure is generated. I'm monitoring the final release of Nx v6 to see if this changes. Once the final lands I'll likely add a new generator (or use `ng update`) to add the proper testing support needed to allow `ng test` to gather up all across libs, xplat and apps.

**Comment by NathanWalker** [comment]
Testing support is now available in `6.1.0` and your workspace can be **auto updated** by using `ng update` 😄however follow this:

1. First open root `package.json` and temporarily remove `"@workspace/scss": "file:libs/scss",`. Related to pending angular cli issue with ng update: https://github.com/angular/angular-cli/issues/10614
2. Now run `ng update @nstudio/schematics`
3. Add back `"@workspace/scss": "file:libs/scss",` to root package.
4. Clean workspace root: `npm run clean`
5. Clean {N} app: `npm run clean.nativescript.[your-app-name]`

This auto updates all {N} apps in your workspace to {N} 4.1.x and webpack 4.x as well as updates run scripts to bundle and AoT for live reload which appears to offer faster live reload as well as reliable .scss updates anywhere. 👍 

You will also now have linting and testing support! 🙌 

### Test xplat including libs altogether

```
ng test xplat
```

This supports xplat/web at moment and other support will come in subsequent updates.

### Test just libs

```
ng test libs
```

### Verify linting

```
npm run lint
```
