### ISSUE TITLE
libs, xplat and app.nativescript should be listed as projects in angular.json

### ISSUE THREAD

**Issue by m-abs** [nstudio/xplat-issues#14]
Hi @NathanWalker 

I'm having some problems using "ng g" on a fresh xplat-project.

For example, adding a backend service to core:
```bash
> ng g service services/backend --module ./libs/core/core.module.ts
Option (project) is required.
```

If I add `core` to `angular.json`.
```json
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "",
  "projects": {
    "core": {
      "root": "libs/core",
      "sourceRoot": "libs/core",
      "projectType": "library"
    }
  },
  "cli": {
    "warnings": {
      "typescriptMismatch": false,
      "versionMismatch": false
    },
    "defaultCollection": "@nstudio/schematics"
  }
}
```
I can generate the service BUT it ends up in `libs/core/src/lib/services/backend.service.ts` and not `libs/core/services/backend.service.ts`.

I think this happens because the directory structure under `libs/core/` differs from new libs generated by the "ng g lib"-command.

I have similar problems generating new code for `libs/features/ui` and I not sure how to generate code for `xplat/nativescript` and `xplat/web`.

As I see it `libs/core`, `libs/utils`, each of `libs/features/*` and `app.nativescript` and their counter-parts under `xplat` should be listed as projects i the `angular.json`.

**Comment by m-abs** [comment]
Hi @NathanWalker 

Minor FYI, they should also be added to `nx.json` or tslint won't run.

**Comment by netwobble** [comment]
@NathanWalker 
Do you expect to support xplat extension to add to angular? (Without nx)??  When is next release timeframe??  I think I saw July?

**Comment by NathanWalker** [comment]
@netwobble Good question. I had debated that but I'd like to stay away from it. The goal with xplat is to honor Nx to the core meaning try to avoid adding too much extra's that may need not be needed.
There will be an update to address a few of these issues early June and add some generators so that's what's up to bat first along with ssr proper support.

**Comment by NathanWalker** [comment]
These are now added in `6.1.0` and your workspace can be auto updated by using `ng update` 😄however follow this:

1. First open root `package.json` and temporarily remove `"@workspace/scss": "file:libs/scss",`. Related to pending angular cli issue with ng update: https://github.com/angular/angular-cli/issues/10614
2. Now run `ng update @nstudio/schematics`
3. Add back `"@workspace/scss": "file:libs/scss",` to root package.
4. Clean workspace root: `npm run clean`
5. Clean {N} app: `npm run clean.nativescript.[your-app-name]`

This auto updates all {N} apps in your workspace to {N} 4.1.x and webpack 4.x as well as updates run scripts to bundle and AoT for live reload which appears to offer faster live reload as well as reliable .scss updates anywhere. 👍 

You will also now have linting and testing support! 🙌 

### Test xplat including libs altogether

```
ng test xplat
```

This supports xplat/web at moment and other support will come in subsequent updates.

### Test just libs

```
ng test libs
```

### Verify linting

```
npm run lint
```

**Comment by emmalivingstone** [comment]
Just as a sidenote to this - does this mean that Nx features like `yarn dep-graph` and 'tags' won't be supported as `xplat` and `libs` folders are listed in the `angular.json` projects array instead of the features themselves like `xplat/web/features/UI`?

**Comment by NathanWalker** [comment]
@emmalivingstone I'm going to look into dep-graph soon. Plan is to certainly have that supported on some level for sure.
