### ISSUE TITLE
Nx workspace-schematic generation support

### ISSUE THREAD

**Issue by emmalivingstone** [nstudio/xplat-issues#16]
Nx supports `ng g workspace-schematic schematic-name`, but when I run this command inside an xplat workspace I get: `Schematic "workspace-schematic" not found in collection "@nstudio/schematics".`

**Comment by NathanWalker** [comment]
Ah thanks for reminder - yes I will add this to the collection.json for fall through on next patch release 👍

**Comment by emmalivingstone** [comment]
Just discovered also I am able to use `ng g c` for component generation but `ng g m` for module generation gives me the same error as above.

**Comment by NathanWalker** [comment]
Thank you - working on an update this weekend for this.

**Comment by NathanWalker** [comment]
@emmalivingstone `6.1.5` published now which adds support for these.

You can use `ng update @nstudio/schematics` and of course will work as expected in a new workspace.
