### ISSUE TITLE
Only if updating existing projects from older xplat versions: Cannot find module './app.module.ngfactory'

### ISSUE THREAD

**Issue by ph55** [nstudio/xplat-issues#18]
Scenario one (working):
1. Generate native script project `ng g app.nativescript sample`.
2. Execute `npm run start.nativescript.sample.android` - works fine.
3. Push to version control.

Scenario two (not working):
1. Pull existing project from version control (npm install etc.)
2. Execute `npm run start.nativescript.sample.android` - not working.
3. `nativescript-sample/app/app.module.ngfactory.d.ts` not generated

Error thrown:
`ERROR in app/main.aot.ts(2,36): error TS2307: Cannot find module './app.module.ngfactory'.`

So either `app.module.ngfactory.d.ts` should be excluded from `.gitignore` or generated if not exist.

Tested on both MacOS & Windows.

**Comment by NathanWalker** [comment]
@ph55 in scenario two did you run `ng update`?
If not try doing this in that existing project:
```
ng update @nstudio/schematics
```
The migrations should add that file for you.

**Comment by ph55** [comment]
When running `ng update @nstudio/schematics`.

- Windows.
  Another error thrown: `Not found : @xplat-apps/scss`

- MacOS

**Comment by NathanWalker** [comment]
That’s a known issue with angular cli actually. See this comment for how to run ng update:
https://github.com/nstudio/xplat-issues/issues/14#issuecomment-394261444

**Comment by ph55** [comment]
Ok, so after removing `file:libs/scss` I did succeed with `ng update @nstudio/schematic`.
But `app.module.ngfactory.d.ts` still not added.

**Comment by NathanWalker** [comment]
Ok @ph55 thank you. Labeling as bug and will resolve in followup migration. It's in there but not sure why it wouldn't add for you. In meantime you can add that file manually by creating it in app directory and just paste these contents:

```
/**
 * A dynamically generated module when compiled with AoT.
 */
export const AppModuleNgFactory: any;

```

**Comment by NathanWalker** [comment]
ng update should add this file now.
