### ISSUE TITLE
Cannot generate new application

### ISSUE THREAD

**Issue by iztokb** [nstudio/xplat-issues#19]
I'm using Ubuntu 16.04., 
AngularCLI : 6.0.1
Node: 8.11.1

I've followed steps as presented here https://nstudio.io/xplat/

Clean install of nrwl/schematics and xplat schematics   
  "@nrwl/schematics": "6.1.0",
  "@nstudio/schematics": "^6.1.5",

However when I try to generate new app  it fails. Please see the attached image  
![image](https://user-images.githubusercontent.com/25145796/41810029-b1a0777e-76f7-11e8-9ea0-3593cb17923d.png). 

As there is no similar issue (at least I couldn't find one) I suspect that it is related to my environment. I have exhausted my ideas about finding the source of this problem.

Any idea what could be the cause of this issue?

**Comment by NathanWalker** [comment]
Try without the targets option? You shouldnt need that there since the ‘app’ generator is a just that - a web app generator.

**Comment by iztokb** [comment]
Same result. I have a feeling that it is linked to the security settings on my machine. 

This mornining I've started to get similar strange behavior in nest/cli as well (which is based on angular/cli). Neither of them is generating folders on my Linux system, on windows they both work as expected.

The only difference is that nest/cli throws unhandled promise rejection warning and angular/cli doesn't.

I'm closing this issue. I'm convinced its not linked to xplat.

Sorry for uneccessary question. Cheers.
