### ISSUE TITLE
Format generated files

### ISSUE THREAD

**Issue by ph55** [nstudio/xplat-issues#21]
After running `npm run format` generated files are changed.
![image](https://user-images.githubusercontent.com/1386622/41921713-23dda3b8-796c-11e8-9baf-0f546d1b914d.png)

Ideally generated files should be already formatted so you won't push changes twice.

**Comment by NathanWalker** [comment]
@ph55 latest 6.1.8 runs all the generators through Nx formatter. Lemme know if you have any further issue 👍
