### ISSUE TITLE
How to generate new features?

### ISSUE THREAD

**Issue by m-abs** [nstudio/xplat-issues#22]
Hi @NathanWalker 

I can't figure out how to generate a new feature.

Lets say I want to create a feature for `login`, what is going to contain everything related to `logins` and `sessions`.

I want to create the shared module in `libs/features/login` and the platform specific modules in `xplat/web/features/login` + `xplat/nativescript/features/login`.

```bash
> ng g library features/login
CREATE libs/features/login/karma.conf.js (971 bytes)
CREATE libs/features/login/ng-package.json (185 bytes)
CREATE libs/features/login/ng-package.prod.json (158 bytes)
CREATE libs/features/login/package.json (174 bytes)
CREATE libs/features/login/src/index.ts (58 bytes)
CREATE libs/features/login/src/test.ts (700 bytes)
CREATE libs/features/login/tsconfig.lib.json (796 bytes)
CREATE libs/features/login/tsconfig.spec.json (272 bytes)
CREATE libs/features/login/tslint.json (252 bytes)
CREATE libs/features/login/src/lib/features-login.module.ts (231 bytes)
CREATE libs/features/login/src/lib/features-login.component.spec.ts (678 bytes)
CREATE libs/features/login/src/lib/features-login.component.ts (280 bytes)
CREATE libs/features/login/src/lib/features-login.service.spec.ts (417 bytes)
CREATE libs/features/login/src/lib/features-login.service.ts (142 bytes)
CREATE libs/features/login/src/lib/features-login.module.spec.ts (398 bytes)
UPDATE angular.json (13504 bytes)
UPDATE package.json (4380 bytes)
UPDATE tsconfig.json (1312 bytes)
UPDATE nx.json (814 bytes)
```

So far so good, but what next?

If I run: 
```bash
 > ng g library nativescript/login --project xplat         
CREATE libs/nativescript/login/karma.conf.js (971 bytes)
CREATE libs/nativescript/login/ng-package.json (189 bytes)
CREATE libs/nativescript/login/ng-package.prod.json (162 bytes)
CREATE libs/nativescript/login/package.json (178 bytes)
CREATE libs/nativescript/login/src/index.ts (62 bytes)
CREATE libs/nativescript/login/src/test.ts (700 bytes)
CREATE libs/nativescript/login/tsconfig.lib.json (800 bytes)
CREATE libs/nativescript/login/tsconfig.spec.json (276 bytes)
CREATE libs/nativescript/login/tslint.json (252 bytes)
CREATE libs/nativescript/login/src/lib/nativescript-login.module.ts (235 bytes)
CREATE libs/nativescript/login/src/lib/nativescript-login.component.spec.ts (706 bytes)
CREATE libs/nativescript/login/src/lib/nativescript-login.component.ts (292 bytes)
CREATE libs/nativescript/login/src/lib/nativescript-login.service.spec.ts (441 bytes)
CREATE libs/nativescript/login/src/lib/nativescript-login.service.ts (146 bytes)
CREATE libs/nativescript/login/src/lib/nativescript-login.module.spec.ts (418 bytes)
UPDATE angular.json (14393 bytes)
UPDATE package.json (4380 bytes)
UPDATE tsconfig.json (1481 bytes)
UPDATE nx.json (866 bytes)
```

The code new library is created in `libs/nativescript/login` and not `xplat/nativescript/features/login` as expected.

If I try to create it as a module:
``` bash
> ng g module features/nativescript/login --project xplat         
CREATE xplat/lib/features/nativescript/login/login.module.spec.ts (267 bytes)
CREATE xplat/lib/features/nativescript/login/login.module.ts (189 bytes)
```

Closer but still not what I expected.

What is the proper way to do generate a feature?

-- Morten

**Comment by NathanWalker** [comment]
Good timing - I’m working through generator support at moment. Planning on having this included in update this week and this helps to hear how you intuitively we’re thinking about using it.

**Comment by NathanWalker** [comment]
@m-abs 
Given an xplat configured workspace with:
* apps/nativescript-viewer
* apps/web-viewer
* apps/web-admin

`ng g feature login --projects=viewer,admin --targets=web,nativescript`

This would auto create the base feature support in:
* `libs` 
* `xplat/web`
* `xplat/nativescript`

Then modify all 3 app targets (1 {N} app and 2 web apps) to have that feature module integrated.

As far as whether routing should be configured:

`ng g feature login --projects=viewer,admin --routing=true --targets=web,nativescript`

It would add a lazy loaded route on the root routes called `login` which would lazy load a module configured inside each target platform.

How does that sound?

Additionally as far as generators go I've been thinking a lot of things, ie, to add plugins which are intended to be shared across a workspace with more than 1 {N} app:
* apps/nativescript-viewer
* apps/nativescript-artist

`ng g xplat-plugin nativescript-pdf-view --projects=viewer,artist`

This would npm install the `nativescript-pdf-view` plugin into the root and auto add references to it to shared across both `nativescript-viewer` and `nativescript-artist` apps.

As far as components:

`ng g component charts --project=viewer --routing=charts --targets=web,nativescript`

This would create a module with a route path `charts` setup to lazy load in the `nativescript-viewer` and `web-viewer` apps (as mentioned above) with a component called `ChartsComponent`

Thoughts?

**Comment by m-abs** [comment]
Hi @NathanWalker 

It may be confusing that you have a `nativescript-viewer` and a `web-viewer` project, but use `---projects=viewer` in the generate command. But that might just be a matter of getting used to it. 

`xplat-plugin` looks great. But I wonder if it could be possible to have a standard profile for generating new apps, with standard features, plugins etc.

About generating components, I'd expect components to belong to features.
Something like
```bash
ng g component my-component --feature login --targets web,nativescript 
```
Generating:
```bash 
libs/features/login/src/lib/base/my-component.base-component.ts
xplat/nativescript/features/login/src/lib/my-component/my-component.component.ts
xplat/web/features/login/src/lib/my-component/my-component.component.ts
```

I'm thinking `pipes`, `services` and `stores` should also belong to a feature.

**Comment by m-abs** [comment]
At the moment I can't generate new stores in our project:

```bash
 > ng g ngrx test --module libs/features/login/src/lib/features-login.module.ts 
Path "/libs/features/login/src/lib/+state/test.effects.spec.ts" does not exist.
```

**Comment by NathanWalker** [comment]
Thanks for this - we can design the gernators however so any and all input you have would be much appreciated.
Sounds like we are thinking along similar lines.

**Comment by NathanWalker** [comment]
@m-abs 
As of @nstudio/schematics 6.1.7, the following generators are now available:

Generators for xplat (shared) code intended to be consumed by any apps/projects in the workspace

* Generate a new feature module in shared code with specified platform support:

`ng g feature register --platforms=nativescript,web`

* Add a component to that new feature module with specified platform support:

`ng g component signup --feature=register --platforms=nativescript,web`

Generators for xplat apps/projects intended for use within specific apps/projects in the workspace

Perhaps you want to generate a feature module for just certain projects and don't need the code shared:

* Generate a new feature module in only the specified projects with lazy loaded routing configured for a new route path called 'register':

`ng g feature register --projects=nativescript-viewer,web-viewer --projectOnly --routing`

* Generate a new feature module in only the specified projects standalone which you can do what you want with:

`ng g feature register --projects=nativescript-viewer,web-viewer`

* Add a component to that new feature module in only the apps/projects specified:

`ng g component signup --feature=register --projects=nativescript-viewer,web-viewer`

Let me know what you think :)
The next update will add directives, pipes and service generators.

**Comment by NathanWalker** [comment]
I’ll look into ngrx stores as well.

**Comment by NathanWalker** [comment]
You can now also generate pipes in `6.1.8` - I'll be posting all this in a new docs page just about generators soon.

## Pipes

* Generate a new pipe for use across any project/app (generates a platform agnostic pipe in `libs/features/ui/pipes`):

`ng g pipe my-pipe`

* Generate a new pipe in specified feature module (generates a platform agnostic pipe in `libs/features/register/pipes`):

`ng g pipe my-pipe --feature=register`

* Generate a new pipe in specified feature module for specified platforms:

`ng g pipe my-pipe --feature=register --platforms=web,nativescript`

> This is useful when you need to build platform specific pipes which behave differently on the given platforms. Generates a platform specific pipe in `xplat/web/features/register/pipes` and `xplat/nativescript/features/register/pipes`

* Generate a new pipe in specified feature module for only the specified projects/apps:

`ng g pipe my-pipe --feature=register --projects=web-viewer`

**Comment by m-abs** [comment]
Hi @NathanWalker 

Thank you for the update it helps a lot.

A few minor details.

```bash
ng g pipe my-pipe --feature=register
```

Generates these file:
```bash
libs/features/register/pipes/my-pipe.pipe.ts
libs/features/register/pipes/index.ts
```
Even if the feature register haven't been created yet.

Is `--platforms` really needed when `mode` is set?

I'd like to create stores in the feature with `ng g ngrx`, but `ng g feature` doesn't create a module under  `libs/features/login` so I don't have a module to bind it to.

**Comment by NathanWalker** [comment]
I was contemplating whether individual pipe, directive, component and service generators should be able to automatically create a feature module if one didn't exist in that case. Likely should however we could also throw with a suggestion to create the feature first. 

If you have `mode` set it could be neat to have it automatically grab whichever platform mode is set instead of require `--platforms` in that case - only problem there is that sometimes folks forget they have a mode set.

> I'd like to create stores in the feature with `ng g ngrx`, but `ng g feature` doesn't create a module under libs/features/login so I don't have a module to bind it to.

I will be introducing support for `ngrx` hopefully this week along with the others which would create a module suffixed with `StateModule` in libs. This could work via a flag to feature or just off the `ngrx` generator - which do you like better?

1. `ng g ngrx --module libs/features/login/login-state.module.ts`
2. `ng g feature login --ngrx` which would create `libs/features/login/login-state.module.ts` and various ngrx boilerplate. Using this option would allow the other variants to also make sense `ng g feature login --ngrx --platforms=web` which would create `xplat/web/features/login/login-state.module.ts` for just a web only state module. `--projects` flag could also be used to target only projects.

**Comment by m-abs** [comment]
> Likely should however we could also throw with a suggestion to create the feature first however maybe you only want a module with pipes and don't want the default component that comes along with ng g feature so idk curious your thoughts?

I think I'd intuitively would expect it to throw an error, like if you refer to a non-existing module.

But I was a little surprised it created a component with the feature, not that it's problem since we'd create at least one component pr. feature in most cases.

> I will be introducing support for ngrx hopefully this week along with the others which would create a module suffixed with StateModule in libs. This could work via a flag to feature or just off the ngrx generator - which do you like better?

I like option 2 better, but I worry that people would accidentally use `ng g ngrx` from `@nrwl/schematics` because that is what their documentation suggests.

**Comment by NathanWalker** [comment]
Agreed - I think I'll have `ngrx` alias the `feature` generator so it would work same no matter which one they use generally. xplat docs would lay focus on `feature` since it would be more broadly versatile for all sorts of generation with the standard options.

As far as default component being created with feature I was on fence about it. Perhaps it allows a flag to ignore creating that component but default would create one - not sure - could go either way.

**Comment by NathanWalker** [comment]
@m-abs all generators are now documented here:
https://nstudio.io/xplat/generators/
