### ISSUE TITLE
Should feature generator with '--platforms=web' create a base component in libs?

### ISSUE THREAD

**Issue by emmalivingstone** [nstudio/xplat-issues#25]
Just got around to trying out the new generators, they are awesome!

I wanted to generate a feature that would only be shared between web apps, so I used `ng g feature feature-name --platforms=web` but this still creates a folder with a base component in 'libs'. Is this just to follow a design choice where every component should extend a base class? In my case this web specific feature contains a component which needs to extend another web-specific base class so I needed to delete the folder from 'libs' manually.

**Comment by NathanWalker** [comment]
Actually that option likely only applies to component generator. I’ll add this to feature as well today.

**Comment by NathanWalker** [comment]
@emmalivingstone `6.1.17` now fixes this 👍  Next time your reset your workspace or reinstall fresh it should work as described above. You can also use `ng update` if you'd like. Lemme know if you encounter any issue, thanks for reporting!
