### ISSUE TITLE
Question/Issue about Prefix when generating xplat

### ISSUE THREAD

**Issue by emmalivingstone** [nstudio/xplat-issues#4]
I noticed when setting up a workspace it doesn't seem to respect the prefix option you pass in the command. If I run:

`create-nx-workspace new-workspace --npm-scope=test`
`ng g xplat --prefix=test`

All my files still use the workspace name ('new-workspace') when importing from the scope, e.g.

`import { BaseComponent } from '@new-workspace/core/base`

I've also tried not setting the --npm-scope option in the initial Nx workspace creation, and just setting the --prefix with the xplat generator with the same result. 

Not sure if it's related but I get the same error I was getting on the admin tool issue when I run the xplat generator, even though it completes the rest of the operation:

IDE Settings could not be updated at this time: { Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:675:18)
    at tryReadSync (fs.js:540:20)
    at Object.fs.readFileSync (fs.js:583:19)
    at Object.updateIDESettings

**Comment by NathanWalker** [comment]
Hi @emmalivingstone - the `prefix` is actually for component prefix and various class name prefixes to make things clear, for example:
https://github.com/nstudio/xplat-sample/blob/master/frontend/xplat/nativescript/features/tags/components/tags/tags.component.ts#L19
https://github.com/nstudio/xplat-sample/blob/master/frontend/xplat/web/features/tags/components/tags/tags.component.ts#L8
https://github.com/nstudio/xplat-sample/blob/master/frontend/xplat/web/core/core.module.ts#L102
and:
https://github.com/nstudio/xplat-sample/blob/master/frontend/xplat/nativescript/core/core.module.ts#L86

The workspace name (barrel name) is purely defined by Nx when you set up the project.
However if you were confused by this, others might as well. I'll leave this open to see. We may consider alternatives. Basically when mixing code together it's good to have a prefix (for components and various modules) which is consistent to be used and consumed all over.

**Comment by emmalivingstone** [comment]
Ah right, I see what you mean for the prefix. But in terms of the barrel name - if you set the Nx workspace up initially using:
`create-nx-workspace another-workspace --npm-scope=test`
When you set up xplat afterwards, should the generated files be importing using the workspace directory name ('another-workspace') or the npmScope ('test')? At the moment it uses the workspace directory name but I would have thought it should default to the npmScope if it is provided. 

It kind of creates a mismatch in the tsconfig.json:
`    "paths": {
      "@test/*": [
        "libs/*"
      ],
      "@another-workspace/*": [
        "libs/*"
      ],`

Whereas the Nx workspace without xplat would only have the 'test' path.

**Comment by NathanWalker** [comment]
Ah @emmalivingstone yes great one. Labeling as bug and will get this 👍

**Comment by NathanWalker** [comment]
@emmalivingstone This is fixed on latest alpha release. To try it out with latest Nx using Angular v6 and NativeScript v4, do the following:

```
npm i -g @nrwl/schematics@next 
create-nx-workspace [project-name]
cd [project-name]
npm i @nstudio/schematics --save-dev
ng g xplat --prefix=[preferred-component-prefix]  // 2-3 character prefix used in xplat
ng g app yourapp
ng g app.nativescript yourapp
```

That would create the structure to get you going. By default now (based on your suggestion), this creates xplat and apps **without** sample `items` feature. 👍 

If you want the sample, you can use the `--sample` flag as follows when first generating:

```
ng g xplat --prefix=[preferred-component-prefix]  --sample
ng g app yourapp --sample
ng g app.nativescript yourapp --sample
```

Nx official 2.x release will likely happen early next week however things look good and you can go ahead and use above to be on the very latest which will best prepare you.
