### ISSUE TITLE
Livesync?

### ISSUE THREAD

**Issue by tblakers** [nstudio/xplat-issues#5]
I'm having difficulty with livesync.

Currently, changes to any file causes the entire application to be redeployed, whereas in a conventional NativeScript structure it's possible to hot-reload changes to the XML/CSS.

Is this a current limitation of xplat, or a mis-configuration on my part?

**Comment by tblakers** [comment]
I should note that switching from IntelliJ to VSCode helped a lot.

On almost every change, IntelliJ invokes an NPM re-index, which consumes 300% of a CPU, rendering the livesync update process almost unusable.

**Comment by NathanWalker** [comment]
I have noticed the same - VSCode seems to be the way to go with this development stack 👍 -- however certainly use whichever IDE you prefer but you may want to make adjustments to it's settings depending.
Angular 6 + NativeScript 4.x support is released and available against an alpha release of Nx which can be tried by following this:
https://github.com/nstudio/xplat-issues/issues/4#issuecomment-387579031

Official release will probably happen this week.
