### ISSUE TITLE
'rm -rf' command in NativeScript app clean script

### ISSUE THREAD

**Issue by emmalivingstone** [nstudio/xplat-issues#7]
On Windows I generated a new NativeScript app within the workspace, and it generated an npm clean script for it which reads:

` "clean.nativescript.test": "cd apps/nativescript-test && rm -rf hooks node_modules platforms package-lock.json && npm i"`

Should the `rm -rf` command be `npx rimraf` to support windows?

**Comment by bradmartin** [comment]
Definitely need a solution to support multiple OS and `rimraf` will work fine.

**Comment by NathanWalker** [comment]
Will adjust this on next release 👍

**Comment by NathanWalker** [comment]
Also need to update `"css.clean": "find app -type f -iname '*.css' -and ! -iname 'font-awesome.min.css' -delete"` as it is not windows friendly.

**Comment by NathanWalker** [comment]
Fixed with latest. See [this comment](https://github.com/nstudio/xplat-issues/issues/4)
