### ISSUE TITLE
'ng test' errors

### ISSUE THREAD

**Issue by emmalivingstone** [nstudio/xplat-issues#8]
Starting off from a new workspace with a web app, running `ng test` gives you a few errors off the bat. For example:

WARNING in C:/Users/emliv/Documents/Monorepo/workspace/libs/core/services/log.service.spec.ts
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\Users\emliv\Documents\Monorepo\workspace\node_modules\@ngtools\webpack\src\index.js!C:\Users\emliv\Documents\Monorepo\workspace\libs\core\services\log.service.spec.ts
    Used by 1 module(s), i. e.
    C:\Users\emliv\Documents\Monorepo\workspace\libs /\.spec\.ts$/
* C:\Users\emliv\Documents\Monorepo\workspace\node_modules\@ngtools\webpack\src\index.js!c:\Users\emliv\Documents\Monorepo\workspace\libs\core\services\log.service.spec.ts
    Used by 1 module(s), i. e.
    C:\Users\emliv\Documents\Monorepo\workspace\apps /\.spec\.ts$/
 @ C:/Users/emliv/Documents/Monorepo/workspace/libs/core/services/log.service.spec.ts
 @ C:/Users/emliv/Documents/Monorepo/workspace/libs \.spec\.ts$
 @ C:/Users/emliv/Documents/Monorepo/workspace/test.js

Also there are ones to do with AppComponent using router-outlet but it not being provided in tests. It might be nice to be able to start off with passing tests like you can with the Angular CLI just so you aren't fixing things from the start, if it's possible!

**Comment by NathanWalker** [comment]
Fixed in latest. Please reopen @emmalivingstone if you find is not fixed on your end with latest.
